### PR TITLE
Handle Record Audio permission more gracefully

### PR DESCRIPTION
**Pull request by tuancoltech**
Handle Record Audio permission more gracefully: 
https://github.com/ARK-Builders/ARK-Memo/issues/66

### CODE REVIEW

**Review by shubertm — CHANGES_REQUESTED** [review]
The code looks good to me. But I think we should request permission on Voice FAB click

**Comment by tuancoltech** [comment]
> The code looks good to me. But I think we should request permission on Voice FAB click

@shubertm As per discussed in our channel, let's keep the current status!

**Comment by shubertm** [comment]
> > The code looks good to me. But I think we should request permission on Voice FAB click
> 
> @shubertm As per discussed in our channel, let's keep the current status!

Feel free to merge then

**Comment by tuancoltech** [comment]
@

> > > The code looks good to me. But I think we should request permission on Voice FAB click
> > 
> > 
> > @shubertm As per discussed in our channel, let's keep the current status!
> 
> Feel free to merge then

@shubertm Will need your approval for merging :)

**Comment by shubertm** [comment]
> @
> 
> > > > The code looks good to me. But I think we should request permission on Voice FAB click
> > > 
> > > 
> > > @shubertm As per discussed in our channel, let's keep the current status!
> > 
> > 
> > Feel free to merge then
> 
> @shubertm Will need your approval for merging :)

Oooh! Sorry, I thought I have already approved :)

**Review by shubertm — APPROVED** [review]
:rocket:

**Pull request merged**
