### PR TITLE
Handle error when the folder is removed externally

### PR DESCRIPTION
**Pull request by tuancoltech**
Handle error when the folder is removed externally
https://app.asana.com/0/1207829522063916/1207809744096491

### CODE REVIEW

**Review by shubertm — COMMENTED** [review]
Works fine in emulator(Android 15). On physical devices(Android 10) it is crashing on fresh start. Uninstall app, install it again, open, crash.

**Comment by tuancoltech** [comment]
> Works fine in emulator(Android 15). On physical devices(Android 10) it is crashing on fresh start. Uninstall app, install it again, open, crash.

@shubertm Could you provide the stack trace of the crash please?
And can you also provide me the bug report by this command?

`adb bugreport > ./bug.zip`

Thanks.

**Comment by shubertm** [comment]
> > Works fine in emulator(Android 15). On physical devices(Android 10) it is crashing on fresh start. Uninstall app, install it again, open, crash.
> 
> @shubertm Could you provide the stack trace of the crash please?
> And can you also provide me the bug report by this command?
> 
> `adb bugreport > ./bug.zip`
> 
> Thanks.

Surprisingly, stacktrace is not printing any error
I will provide the report

**Comment by shubertm** [comment]
https://github.com/user-attachments/assets/49a89039-7f35-4b16-b30f-3f0e88b94d3f

- [ ] There is need to detect deleted folder while notes are loaded to avoid opening deleted notes
- [ ] Should also apply where note is already opened

**Comment by tuancoltech** [comment]
> Works fine in emulator(Android 15). On physical devices(Android 10) it is crashing on fresh start. Uninstall app, install it again, open, crash.

@shubertm Can you provide a video record providing the flow overview which leads to crash?

**Comment by tuancoltech** [comment]
> * There is need to detect deleted folder while notes are loaded to avoid opening deleted notes

@shubertm This will be covered by `fs-index` when Memo is fully integrated with new `ark-core` library.
For now, we'll not do background monitoring of files change in Memo.

**Comment by shubertm** [comment]
> > Works fine in emulator(Android 15). On physical devices(Android 10) it is crashing on fresh start. Uninstall app, install it again, open, crash.
> 
> @shubertm Can you provide a video record providing the flow overview which leads to crash?

https://github.com/user-attachments/assets/3273645b-7151-4e9d-a4e1-81e405643c00

**Comment by tuancoltech** [comment]
> > > Works fine in emulator(Android 15). On physical devices(Android 10) it is crashing on fresh start. Uninstall app, install it again, open, crash.
> > 
> > 
> > @shubertm Can you provide a video record providing the flow overview which leads to crash?
> 
>  SVID_20241207_110056_1.mp4

@shubertm  This crash is happening in `main` branch as well, and only Android 10 (and probably 8, 9 too).
So, it’s not related to the changes made in in this PR.

Please continue testing & reviewing the PR. 
For the crash, I’ve created a different ticket for it here: https://app.asana.com/0/1207819682524134/1208903376779601.

Will investigate and fix in another branch.

**Review by shubertm — APPROVED** [review]
Looks good :+1:

**Comment by shubertm** [comment]
> > * There is need to detect deleted folder while notes are loaded to avoid opening deleted notes
> > * Should also apply where note is already opened
> 
> @shubertm This will be covered by `fs-index` when Memo is fully integrated with new `ark-core` library. For now, we'll not do background monitoring of files change in Memo.

@tuancoltech do we a ticket for this already in Asana?

**Comment by tuancoltech** [comment]
> > > * There is need to detect deleted folder while notes are loaded to avoid opening deleted notes
> > > * Should also apply where note is already opened
> > 
> > 
> > @shubertm This will be covered by `fs-index` when Memo is fully integrated with new `ark-core` library. For now, we'll not do background monitoring of files change in Memo.
> 
> @tuancoltech do we a ticket for this already in Asana?

@shubertm Not really, we just discussed about it over Telegram.
However, just in case you need a related Asana ticket, I think you can take a look here: https://app.asana.com/0/1207829522063916/1208782130889593

**Pull request merged**
