### PR TITLE
#2: Voice notes

### PR DESCRIPTION
**Pull request by shuberttheI**
- #2

### CODE REVIEW

**Comment by tuancoltech** [comment]
@ShubertMunthali Could you please rebase the branch with `main` to remove the merge conflicts first?

**Comment by ShubertMunthali** [comment]
> @ShubertMunthali Could you please rebase the branch with `main` to remove the merge conflicts first?

Alright @tuancoltech

**Comment by kirillt** [comment]
Basic recording works. There are some issues, but I'm sure we can polish the app from this point.

**Review by kirillt — APPROVED** [review]
It works good, only need to catch up with `main`.

**Comment by ShubertMunthali** [comment]
> It works good, only need to catch up with `main`.

Alright, we will catch up soon

**Pull request merged**
