### PR TITLE
Extract methods to interfaces & change way of providing dependencies

### PR DESCRIPTION
**Pull request by hieuwu**
## :rocket: Summary
Extract methods to interfaces & change way of providing dependencies
Part 1 of #24

- Avoid usage of manual singleton, replace with singleton component
- Extract methods to interface to make the app ready for TDD

All new repository created must follow the principle `programming over abstraction instead of implementation`.
They should be provided in `di` and as a module

### CODE REVIEW

**Review by ShubertMunthali — CHANGES_REQUESTED** [review]
```TextNotesRepo``` interface should be renamed ```NotesRepo``` and ```TextNotesRepoImpl``` to just ```TextNotesRepo```. We will have other note type repos implement it

**Review by ShubertMunthali — COMMENTED** [review]
We should migrate to ```Datastore``` later
https://developer.android.com/topic/libraries/architecture/datastore

**Comment by hieuwu** [comment]
> `TextNotesRepo` interface should be renamed `NotesRepo` and `TextNotesRepoImpl` to just `TextNotesRepo`. We will have other note type repos implement it

Got your point. However, let's keep one implementation for one interface as it is current approach. If in the future we add more, let's consider later.

**Comment by hieuwu** [comment]
> We should migrate to `Datastore` later https://developer.android.com/topic/libraries/architecture/datastore

I just change the way to provide dependencies. If we need to migrate to data store, we should do it later

**Review by ShubertMunthali — APPROVED** [review]
Looks good, thanks

**Pull request merged**
